version: '3.8'

services:
  backend:
    container_name: nest-docker-postgres
    build: .
    environment:
      - DATABASE_HOST=task_db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=task_db
      - JWT_SECRET=secret
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    networks:
      - task-track-database_development

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-track-database_development

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - task-track-database_development

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - task-track-database_development

volumes:
  postgres_data:

networks:
  task-track-database_development:
    external: true
